---
minio:
  # endpoint: "minio-ott.nsc.iudanet.com:443"
  endpoint: "minio.example.tld:443"

  accessKey: "accessKey"
  secretKey: "secretKey"
  useSSL: true

cleaner:
  maxObjectsPerRun: 100  # Можно изменить на нужное значение
